services:
  - type: web
    name: nyota-fund
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn nyota_fund.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: TUMA_API_URL
        value: 'https://api.tuma.co.ke'
      - key: TUMA_SHOP_EMAIL
        sync: false
      - key: TUMA_API_KEY
        sync: false
      - key: TUMA_CALLBACK_URL
        value: 'https://nyota-foundations16.onrender.com/api/mpesa/callback/'
