services:
  - type: web
    name: nyota-fund
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn nyota_fund.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: PAYNEXUS_API_URL
        value: 'https://api.paynexus.co.ke/v1'
      - key: PAYNEXUS_SHOP_EMAIL
        sync: false
      - key: PAYNEXUS_API_KEY
        sync: false
      - key: PAYNEXUS_CALLBACK_URL
        value: 'https://nyota-foundation32.onrender.com/api/mpesa/callback/'




